checkservices: Rework options handling

diff --git a/checkservices b/checkservices
--- a/checkservices
+++ b/checkservices
@@ -23,9 +23,9 @@
 unset GREP_OPTIONS
 
 # Systemd cgroup path
-systemd_cgroup_base_path='/sys/fs/cgroup/systemd'
+SYSTEMD_CGROUP_BASE_PATH='/sys/fs/cgroup/systemd'
 
-
+# colors
 if [[ -t 1 ]]; then
 	shopt -s xpg_echo
 	c_title='\e[1;33m'
@@ -35,19 +35,32 @@ if [[ -t 1 ]]; then
 	c_rst='\e[m'
 fi
 
+# default options
+dbus=1				# relauch when dbus
+failed=1			# display failed service at the end
+pacdiff=1 			# run pacdiff
+reload=1 			# reload systemd
+serialize=0			# run in parallel
+status=1 			# display status after systemctl
+systemctl='' 		# systemctl command to call
+user_slice=0		# act on users services
+verbose=0			# more details
+
 usage() {
 	echo "usage ${0##*/} [options]"
+	echo "description: check for updated files in a service"
 	echo 'options:'
-	echo '   -h: this help' >&2
-	echo '   -r: restart services' >&2
-	echo '   -R: reload services' >&2
-	echo "   -s: serialize action" >&2
-	echo "   -p: don't call pacdiff before action" >&2
-	echo "   -n: don't call systemd daemon-reload" >&2
-	echo "   -N: don't display status of restart/reload units" >&2
-	echo "   -u: list service in users slice" >&2
-	echo "   -v: verbose mode" >&2
-	exit 1
+	echo '  -h: this help' >&2
+	echo "  -b/-B: restart (or not) ${0##*/} if dbus was updated (default: $dbus)" >&2
+	echo "  -d/-D: call (or not) systemd daemon-reload (default: $reload)" >&2
+	echo "  -f/-F: display (or not) failed services before quit (default: $failed)" >&2
+	echo "  -p/-P: call (or not) pacdiff before act (default: $pacdiff)" >&2
+	echo "  -r/-R: restart (or reload) services (default: $systemctl)" >&2
+	echo "  -s/-S: display (or not) status of restarted service (default: $status)" >&2
+	echo "  -u/-U: act (or not) on services in users slice (default: $user_slice)" >&2
+	echo "  -v/-V: verbose mode (or disable it)" >&2
+	echo "  -z/-Z: serialize (or not) action (default: $serialize)" >&2
+	exit 2
 }
 
 # usage : in_array( $needle, $haystack )
@@ -62,17 +75,17 @@ in_array() {
 	return 1 # Not Found
 }
 
-while getopts 'hrRsnNuvp' opt; do
+while getopts 'hBbDdFfPpRrSsUuVvZz' opt; do
 	case $opt in
-		r) systemd_cmd='restart';;
-		R) systemd_cmd='reload';;
-		s) serial=true;;
-		n) no_reload=1;;
-		N) no_status=1;;
-		p) no_pacdiff=1;;
-		l) list=true;;
-		u) user_slice=true;;
-		v) verbose=true;;
+		B) dbus=0;; 			b) dbus=1;;
+		D) reload=0;;			d) reload=1;;
+		F) failed=0;;			f) failed=1;;
+		P) pacdiff=0;;			p) pacdiff=1;;
+		R) systemctl='reload';; r) systemctl='restart';;
+		S) status=0;;			s) status=1;;
+		U) user_slice=0;;		u) user_slice=1;;
+		V) verbose=0;;			v) verbose=1;;
+		Z) serialize=0;;		z) serialize=1;;
 		*) usage;;
 	esac
 done
@@ -86,16 +99,17 @@ trap '' SIGHUP
 (( $UID != 0 )) && echo 'You need to be root' && exit 1
 
 # call pacdiff
-[[ -z $no_pacdiff ]] && pacdiff
+(( pacdiff )) && pacdiff
 
 # reload units list
-[[ -z $no_reload ]] && systemctl --system daemon-reload
+(( reload )) && systemctl --system daemon-reload
 
 # list of running services
 declare -a services
 services=($(systemctl --no-legend --full --type service --state running|cut -f1 -d' '))
 
 # list of bus names
+declare -a buses
 buses=($(dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames|sed -rn 's/\s*string "(.*)"/\1/p'))
 
 # beggar count
@@ -105,19 +119,18 @@ declare -i pid=0
 for svc in "${services[@]}"; do
 	unit_path="$(systemctl -p ControlGroup show "$svc"|cut -f 2 -d=)"
 	busname="$(systemctl -p BusName show "$svc"|cut -f 2 -d=)"
-	tasks_path="$systemd_cgroup_base_path/$unit_path/tasks"
+	tasks_path="$SYSTEMD_CGROUP_BASE_PATH/$unit_path/tasks"
 	[[ -e "$tasks_path" ]] || {
 		echo "${c_error}** Unable to get pid of $svc: No tasks file: $tasks_path${c_rst}" >&2
 		continue
 	}
 	# check if unit is in system slice
-	[[ "$unit_path" =~ /user\.slice/ && ! "$user_slice" == true ]] && continue
-	pids=( $(< "$systemd_cgroup_base_path/$unit_path/tasks") )
+	(( user_slice )) && [[ "$unit_path" =~ /user\.slice/ && ! "$user_slice" == true ]] && continue
+	pids=( $(< "$SYSTEMD_CGROUP_BASE_PATH/$unit_path/tasks") )
 	if (( "${#pids[*]}" == 0 )); then
 		echo "${c_error}** Unable to get pid of $svc: Tasks file is empty${c_rst}" >&2
 		continue
 	fi
-	deleted=''
 	for pid in "${pids[@]}"; do
 		maps_path="/proc/$pid/maps"
 		[[ -e "$maps_path" ]] || {
@@ -127,27 +140,25 @@ for svc in "${services[@]}"; do
 		deleted=$(grep -F '(deleted)' "$maps_path" |sed -nr 's|^\S+ ..x. \S+ \S+ \S+ \s+||p'|sort|uniq)
 		if [[ -n $deleted ]] || { [[ -n "$busname" ]] && ! in_array "$busname" "${buses[@]}"; }; then
 			needy+=("$svc")
-			if [[ $verbose ]]; then
+			if (( verbose )); then
 				echo "${c_title}Service:${c_svc} $svc${c_rst}"
 				echo "${c_title}Pid:${c_rst} $pid"
 				echo "${c_title}Bus:${c_rst} $busname"
-				echo "${c_title}Commands:${c_rst}"
-				echo "systemctl reload '$svc'"
-				echo "systemctl restart '$svc'"
-				echo -n "${c_title}BusName on the system bus: ${c_rst}"
+				echo "${c_title}Commands:${c_rst} systemctl ${systemctl:-restart} '$svc'"
+				echo -n "${c_title}BusName detected on the system bus: ${c_rst}"
 				in_array "$busname" "${buses[@]}" && echo 'Yes' || echo 'No'
 				echo "${c_title}Deleted files:${c_rst}"
 				echo "$deleted"
 				echo
 			else
-				echo "systemctl restart '$svc'"
+				echo "systemctl ${systemctl:-restart} '$svc'"
 			fi
-			if [[ $systemd_cmd ]]; then
-				systemctl "$systemd_cmd" "$svc" &
+			if [[ -n $systemctl ]]; then
+				systemctl "$systemctl" "$svc" &
 				# wait process to terminate when serialize
-				[[ -n $serial ]] && wait
-				# display status directly when not serialize
-				[[ -n $serial && -z $no_status ]] && systemctl --lines=0 status "$svc"
+				(( serialize )) && wait
+				# display status directly when serialize and not quiet
+				(( serialize )) && (( status )) && systemctl --lines=0 status "$svc"
 			fi
 			break
 		fi
@@ -156,20 +167,16 @@ done
 wait
 
 # show units status
-if [[ -z $serial && -z $no_status && $systemd_cmd && ${needy[*]} ]]; then
+if (( serialize == 0 )) && (( status )) && [[ -n $systemctl && -n ${needy[*]} ]]; then
 	systemctl --lines=0 status "${needy[@]}"
 fi
 
-if [[ $verbose ]]; then
-	systemctl --failed --all --no-pager --full list-units
-else
-	systemctl --failed --all --no-pager --no-legend --full list-units
-fi
+(( failed )) && systemctl --failed --all --no-pager --no-legend --full list-units
 
 # warn if dbus was restart
 if in_array dbus.service "${needy[@]}"; then
 	echo "${c_warn}After dbus restart, you should run ${0##*/} twice${c_rst}" >&2
-	if [[ -n "$systemd_cmd" && -z $CHECKSERVICE_WAS_RESTARTED ]]; then
+	if (( dbus )) && [[ -n $systemctl && -z $CHECKSERVICE_WAS_RESTARTED ]]; then
 		echo "${c_warn}Doing it for you. No need to thanks me!${c_rst}" >&2
 		export CHECKSERVICE_WAS_RESTARTED=1
 		exec "$0" "$@"
